sudo: false

language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: nightly
  include:
    - php: '5.3'
      dist: precise
    - php: '5.4'
      dist: trusty
    - php: '5.5'
      dist: trusty

before_script:
  - travis_retry composer install --no-interaction --prefer-dist --optimize-autoloader

script:
  - bin/create-idnamap.sh --debug test/assets/IdnaMappingTable.txt -
  - ./vendor/bin/phpunit

notifications:
  email: false
